[package]
name = "quickstart-rs"
version = "0.1.0"
edition = "2021"
authors = ["Vikas Poddar"]
description = "This is a package for learning about rust programming language"
repository = "https://github.com/vikaspoddar/quickstart-rs"
license = "MIT"
[dependencies]
quick-lib = "0.1.23"
